[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["ws"] }
game_core = { version = "0.1.0", path = "../game_core" }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net", "sync"] }

[dev-dependencies]
futures-util = "0.3.34"
tokio = { version = "1.53.1", features = ["time"] }
tokio-tungstenite = "0.30.0"
